### PR TITLE
feat: create infra to run non-jscodeshift codemods & create 1st postcss transform postcss-replace-simple-variables

### PR DESCRIPTION
**Pull request by kiprasmel**
https://pipedrive.atlassian.net/browse/CTR-38

### CODE REVIEW

**Comment by isaacagaba** [comment]
Hi, I was trying out your branch and I think you missed out adding this package 
image

**Comment by kiprasmel** [comment]
hey @isaacagaba, i'm afraid i cannot easily reproduce. is it still an issue? if so - could you give the repo(s) you were using & the directories to run on?

**Comment by isaacagaba** [comment]
> hey @isaacagaba, i'm afraid i cannot easily reproduce. is it still an issue? if so - could you give the repo(s) you were using & the directories to run on?

it might have been something related with running **npm install** , when I switched to `yarn install ` this error disappeared

**Comment by kiprasmel** [comment]
@isaacagaba ah okay. yes, we're using yarn-specific features here that npm doesn't support (yet?) and yes you need to use yarn. i can update the readme to say `yarn install` instead of `yarn`, because they are the same, but perhaps for ppl who've used npm for a while, it isn't clear. thanks!

**Comment by kiprasmel** [comment]
LGTM

**Pull request merged**
